Performance test prototype
andromeda/pash pull request #107
Opened 2021-01-28 21:04 UTC by zyrolasting

This revision adds Unix50 and EuroSys one liner performance tests, using `-m`.

As of this writing, `memstar.ndr.md` is now configured to use the `workers/run-perf.sh` script, and `ci.pash.ndr.md` are now listening on port 2048 to manage `memstar.ndr.md`. Go ahead and run `curl ci.pash.ndr.md:2048/stdout` to see where the tests are right now. :)

Notes:

* @angelhof: The Dockerfile has been updated to declare a locale. I ended up needing to do this to get past more and more Python errors when running scripts. Can you help me verify that this will not negatively impact artifacts?
* I updated all worker scripts to use empty directories for locks, since `mkdir` is atomic.
* The correctness test configuration has been updated to use less code, since the performance test controller needed to share some functionality.
* @nvasilakis: Despite what we discussed, I ended up downloading the entire results directory. It turned out to be pretty fast (< 1s) for me, and since it's using `rsync` I trust that the controller will download only incremental changes from then on. Let me know if this is okay with you.

2021-01-28 22:25 UTC, angelhof requested changes
Thanks a lot! I reviewed the parts of the code that I understand (so I didn't check the ci infrastructure changes in detail). 

Regarding the unix benchmarks, I think that there is no `-m` flag. Did you change the script to support one?

Except for that (and the Dockerfile nit), everything looks good!

2021-01-28 22:25 UTC, angelhof commented on scripts/Dockerfile
> +RUN apt-get install -y locales locales-all
Nit: Maybe these should be moved with the `apt-get`s above

2021-01-28 22:25 UTC, angelhof commented on scripts/remote/workers/run-perf.sh
> +    run ./execute_unix_benchmarks.sh -m
Does `execute_unix_benchmarks.sh` actually support `-m`? I think it just supports `-s` and `-l` :)

2021-01-28 22:26 UTC, angelhof commented
> @angelhof: The Dockerfile has been updated to declare a locale, fixing #106. I ended up needing to do this to get past more and more Python errors when running scripts. Since we discussed it before, can you help me verify that this will not negatively impact artifacts?

Since you were able to run the perf tests it should be fine!

2021-01-28 22:33 UTC, zyrolasting commented
@angelhof Requested changes are in. Thanks!

2021-01-28 23:55 UTC, nvasilakis approved these changes
Awesome! I haven't tested, I'm assuming we're firing this on beta/memstar for a few days and monitor the results:-)

2021-01-28 23:56 UTC, nvasilakis commented
> * @nvasilakis: Despite what we discussed, I ended up downloading the entire results directory. It turned out to be pretty fast (< 1s) for me, and since it's using `rsync` I trust that the controller will download only incremental changes from then on. Let me know if this is okay with you.

Sounds good!

2021-01-29 01:23 UTC, angelhof approved these changes

2021-01-29 01:23 UTC, merged